### ISSUE TITLE
Режим listen игнорирует изменение файлов

### ISSUE THREAD

**Issue by kovalevsky** [httplab/insup#18]
Проблема воспроизводится после обновления до OS X 10.10.

Лог установки insup:

```
sk@skbook:~% rvm list

rvm rubies

=* ruby-2.1.2 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

sk@skbook:~% gem install insup
Fetching: colorize-0.7.3.gem (100%)
Successfully installed colorize-0.7.3
Fetching: gli-2.12.2.gem (100%)
Successfully installed gli-2.12.2
Fetching: ffi-1.9.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.6
Fetching: rb-inotify-0.9.5.gem (100%)
Successfully installed rb-inotify-0.9.5
Fetching: rb-fsevent-0.9.4.gem (100%)
Successfully installed rb-fsevent-0.9.4
Fetching: hitimes-1.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.2
Fetching: timers-4.0.1.gem (100%)
Successfully installed timers-4.0.1
Fetching: celluloid-0.16.0.gem (100%)
Successfully installed celluloid-0.16.0
Fetching: listen-2.7.11.gem (100%)
Successfully installed listen-2.7.11
Fetching: match_files-0.2.gem (100%)
Successfully installed match_files-0.2
Fetching: thread_safe-0.3.4.gem (100%)
Successfully installed thread_safe-0.3.4
Fetching: minitest-5.4.2.gem (100%)
Successfully installed minitest-5.4.2
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.beta1.gem (100%)
Successfully installed i18n-0.7.0.beta1
Fetching: activesupport-4.2.0.beta2.gem (100%)
Successfully installed activesupport-4.2.0.beta2
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: activemodel-4.2.0.beta2.gem (100%)
Successfully installed activemodel-4.2.0.beta2
Fetching: rails-observers-0.1.2.gem (100%)
Successfully installed rails-observers-0.1.2
Fetching: activeresource-4.0.0.gem (100%)
Successfully installed activeresource-4.0.0
Fetching: insup-0.3.gem (100%)
type 'insup help' for help
Successfully installed insup-0.3
20 gems installed
```

Конфиг insup:

```
sk@skbook:~% cat .insup
track:
  - media
  - templates
  - snippets
  - config  

tracker:
  class: git

insales:
  subdomain: ***
  api_key: ***
  password: ***

uploader:
  class: insales
  theme_id: ***

ignore:
  - '*.swp'
  - '*.swx'
  - '.*'
  - 'thumbs.db'
  - '.DS_Store'

log:
  file: log/insup.log
  level: 'debug'
  pattern: "%{timestamp} - %{level}\t: %{message}\n"%
```

Изменения порядка и состава директорий в `track` к видимым изменениям не приводят.
После выполнения команды `insup listen` отображается только `Listening...`.
